code --install-extension aprilandjan.vscode-node-debug-process-picker
code --install-extension arcanis.vscode-zipfs
code --install-extension basdp.language-gas-x86
code --install-extension dan-c-underwood.arm
code --install-extension formulahendry.vscode-mysql
code --install-extension grapecity.gc-excelviewer
code --install-extension jebbs.plantuml
code --install-extension marus25.cortex-debug
code --install-extension maziac.asm-code-lens
code --install-extension mcu-debug.debug-tracker-vscode
code --install-extension mcu-debug.memory-view
code --install-extension mcu-debug.peripheral-viewer
code --install-extension mcu-debug.rtos-views
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.makefile-tools
code --install-extension pedrotavares.myzoom
code --install-extension puorc.awesome-vhdl
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension shardulm94.trailing-spaces
code --install-extension stmicroelectronics.stm32-vscode-extension
code --install-extension tomoki1207.pdf
code --install-extension trond-snekvik.gnu-mapfiles
code --install-extension twxs.cmake
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension xsro.masm-tasm
code --install-extension xsro.vscode-dosbox
code --install-extension zixuanwang.linkerscript