@startuml Grammar class

    class Grammar{

        -nonTerminalSymbol:ArrayList<String>
        -terminalSymbol:ArrayList<String>
        -startSymbol:String 
        -production:ArrayList<Production>  

        +Grammar(nonTerminalSymbol:ArrayList<String>,terminalSymbol:ArrayList<String>,startSymbol:String,production:ArrayList<Production> )
        +getNonTerminalSymbols():ArrayList<String>
        +getTerminalSymbols():ArrayList<String>
        +getStartSymbol():String
        +getProductions():ArrayList<Production>
        -isTerminal(string:String):boolean
        +leftMostDerivation(vocabularySize:int,maxWordSize:int):ArrayList<String>
    }
@enduml