@startuml Production class

    class Production{
        
        -inputSymbol:String 
        -output:ArrayList<String> 

        +Production(inputSymbol:String,ouput:ArrayList<String>)
        +getInputSymbol():String
        +getOutput():ArrayList<String>
        +applyRule(symbol:String):String

    }
@enduml