LOGIC_DIR=logic
MAIN_DIR=main
MAIN_CLASS=Main

all:
#compile and run Java code
	javac $(MAIN_DIR)/$(MAIN_CLASS).java 
	java $(MAIN_DIR).$(MAIN_CLASS)

clean:
#clean Java bytecode
	rm $(LOGIC_DIR)/*.class $(MAIN_DIR)/*.class 